### PR TITLE
Update gulpfile.js

### PR DESCRIPTION
**Pull request by andrewdacenko**
Use on('error') and this.emit('end) to stop the task without crashing

### CODE REVIEW

**Comment by wips** [comment]
Tried that on my env. It runs tests, then starts watch, but does nothing on file change

**Comment by wips** [comment]
Does it work on your env?

**Comment by andrewdacenko** [comment]
@wips updated. Missed update to watch

**Comment by wips** [comment]
Thanks mate! It works just perfect

**Pull request merged**
